# Generated by Django 5.2.1 on 2025-05-07 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('primary_color', models.CharField(default='#2563EB', max_length=20)),
                ('title', models.CharField(default='Support Chat', max_length=100)),
                ('welcome_message', models.TextField(default='Hello! How can I help you today?')),
                ('allowed_domains', models.TextField(blank=True, help_text='Comma-separated list of domains where widget can be embedded')),
                ('enable_file_upload', models.BooleanField(default=False)),
                ('enable_feedback', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
